### ISSUE TITLE
Esquema elétrico

### ISSUE THREAD

**Issue by celsopadilha** [jrbenito/PIMA#1]
Olá, como você montou o esquema elétrico? Estou com dificuldades em um Modelo Cronos 7023-NG

**Comment by jrbenito** [comment]
Olá @celsopadilha ,

No caso do Nansen Vector PAR, a saída PIMA é um coletor aberto, o esquema de coletor aberto é esse aqui: https://en.wikipedia.org/wiki/Open_collector

Você conecta o terra (comum, ground) ao GND do seu circuito, a "perna" denominada "open colector" na figura, você liga ao RX do controlador, também conecte a um resistor e a outra ponta desse resistor vai a VCC. Olha a figura 3 desse link: http://labdegaragem.com/profiles/blogs/open-collector. Nessa figura, R1 e Q1 estão dentro do Cronos, é o coletor aberto. O valor de R2 você precisa calcular conforme a corrente máxima suportada pelo transistor (Q1) do cronos e baseado, claro, no seu VCC (que acredito é 5V ou 3V3 dependendo do controlador). O valor de corrente e tensão suportados pelo Q1 você encontra na documentação do Cronos. O pino B da figura representa o RX do seu microcontrolador.

Att,
Benito

**Comment by jrbenito** [comment]
vc me mostrou que eu esqueci de subir o código aqui!!

**Comment by celsopadilha** [comment]
Ainda estou na luta com o pessoal pra resolver algumas questões na leitura, se você conseguir enviar o código iria ajudar bastante. Abraços

**Comment by celsopadilha** [comment]
Também achei esse link da Copel que ajudou bastante

https://www.copel.com/hpcopel/root/pagcopel2.nsf/0/4310F832B8AD31D00325776F005DCDDB/$FILE/ETC311%20Saida%20Serial%20Medidores%20eletronicos.pdf

**Comment by jrbenito** [comment]
> Ainda estou na luta com o pessoal pra resolver algumas questões na leitura, se você conseguir enviar o código iria ajudar bastante. Abraços

@celsopadilha 

Olha esse projeto meu: https://github.com/jrbenito/PIMA-node

O código nele faz leitura de um relógio com PIMA (da Nansen) e funcionou por 1,5 ano sem problemas num arduino com radiotransmissor RFM69. 
Dele eu iria derivar a biblioteca para esse projeto aqui mas nunca terminei e como vendi o medidor e me mudei para o Canada, provavelmente não farei mais.
